[domain]
domain_size = 1.0
mesh_size = 32
box_size_mpc = 16

[cosmology]
omega_baryon = 0.048
omega_M = 0.3
omega_lambda = 0.7
hubble_param = 0.7
expanding_universe = true

[initial_conditions]
spectral_index = 0.96
start_a = 0.02
sigma_8 = 0.81
initial_gas_temp_k = 50
n_per_side = 32
standing_particles = false
seed = 42

[hydro]
use_hydro = true
gamma = 1.6666666667

[p3m]
use_pm = true
use_pp = true
cutoff_radius_cells = 2.5
cutoff_transition_width_factor = 0.2

[time]
# The timestep is dt_factor * dynamical_time
dt_factor = 1e-3
cfl_safety_factor = 0.5
max_scale_factor = 1.0

[output]
save_hdf5_every_delta_a = 0.005
debug_info_every_cycles = 40
enable_energy_diagnostics = true