[domain]
domain_size = 1.0
mesh_size = 32

[matter]
omega_baryon = 0.15
n_per_side = 32
use_hydro = true

[physics]
# G = 1.0 / (6 * M_PI)
g_const = 0.0530516477
gamma = 1.6666666667
standing_particles = false
expanding_universe = true
expansion_start_t = 0.005
initial_power_spectrum_index = -2.0
sigma_RMS = 0.04

[p3m]
use_pm = true
use_pp = true
cutoff_radius_cells = 2.0
cutoff_transition_width_factor = 0.2

[time]
# The timestep is dt_factor * dynamical_time
dt_factor = 1e-4
max_scale_factor = 1.0

[output]
save_hdf5_every_cycles = 100
debug_info_every_cycles = 40
enable_energy_diagnostics = true
seed = 42

